export const initialFlowObject = {
  inputFullText: undefined,
  inputLastNorm: undefined,
  inputPrevNorm: undefined,
  showGlosaDef: false,
  showAnalogDef: false,
  hasInput: false,
  glosaEntries: [],
  glosaData: {},
  synonymKeyData: [],
  analogKeyData: null,
  analogData: null,
  activeList: null,
  synonymData: { plain_text: "", entries: [] },
  ptBRExtendedS: null,
  ptBRExtendedC: null,
  ptBRExtendedE: null,
  method: undefined,
  isSugDisabled: true,
  activeSug: null,
  activeFlag: null,
  flagGroup: "adv_adj_sub_Flags",
  silaba: null,
  esperar: null,
  showSuggestion: false,
  showWikcio: true,
  showDicio: false,
  wikcioData: null,
  dicioData: null
}